INSERT INTO joints_structure (id, joint_id, joint_name, structure_id, structure_name, category_name, relationship, injury_frequency, notes, created_at, test_in_1, test_in_2, test_out_1, nerve_test_1, nerve_test_2, nerve_test_3) VALUES
(7,2,'CERVICAL',1101,'Sternocleidomastoid (SCM)','Muscle','PRIMARY_MOVER','COMMON',NULL,'2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(8,2,'CERVICAL',1109,'Cervical intervertebral disc','Disc','PASSIVE_SUPPORT','VERY_COMMON','Disc bulge/herniation','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(9,2,'CERVICAL',1112,'Facet joint (zygapophyseal)','Bone / Articular surface','PASSIVE_SUPPORT','VERY_COMMON','Facet syndrome','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(10,2,'CERVICAL',1111,'Cervical nerve roots','Nerve','NEURO','COMMON','Radiculopathy','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(51,2,'CERVICAL',1113,'Upper trapezius','Muscle','PRIMARY_MOVER','COMMON','Neck extension assist + scap elevation','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(52,2,'CERVICAL',1114,'Levator scapulae','Muscle','PRIMARY_MOVER','COMMON','Neck lateral flexion + scap elevation','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(53,2,'CERVICAL',1115,'Scalenes','Muscle','PRIMARY_MOVER','COMMON','Neck flex/lateral flex; accessory breathing','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(54,2,'CERVICAL',1116,'Deep neck flexors (longus capitis/colli)','Muscle','STABILIZER','COMMON','Segmental stability + flexion','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(55,2,'CERVICAL',1117,'Splenius capitis/cervicis','Muscle','PRIMARY_MOVER','COMMON','Extension + ipsilateral rotation','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(56,2,'CERVICAL',1118,'Semispinalis capitis/cervicis','Muscle','STABILIZER','UNCOMMON','Cervical extension control','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)'),
(57,2,'CERVICAL',1119,'Suboccipital muscles','Muscle','STABILIZER','UNCOMMON','Upper cervical control (fine motion)','2026-02-20 05:10:36', 'Spurling Test','Cervical Distraction','Sharp-Purser Test', 'Dermatome C5','Myotome C6 (Wrist Ext)','Biceps Reflex (C5-C6)');
