INSERT INTO joints_structure (id, joint_id, joint_name, structure_id, structure_name, category_name, relationship, injury_frequency, notes, created_at, test_in_1, test_in_2, test_out_1, nerve_test_1, nerve_test_2, nerve_test_3) VALUES
(11,3,'ELBOW',1203,'Common extensor tendon','Tendon','PRIMARY_MOVER','VERY_COMMON','Tennis elbow','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(12,3,'ELBOW',1204,'Common flexor tendon','Tendon','PRIMARY_MOVER','COMMON','Golfer’s elbow','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(13,3,'ELBOW',1208,'Ulnar nerve','Nerve','NEURO','COMMON','Cubital tunnel','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(14,3,'ELBOW',1210,'Olecranon bursa','Bursa','ASSOCIATED','UNCOMMON',NULL,'2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(58,3,'ELBOW',1211,'Biceps brachii','Muscle','PRIMARY_MOVER','COMMON','Elbow flexion + supination','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(59,3,'ELBOW',1212,'Brachialis','Muscle','PRIMARY_MOVER','COMMON','Primary elbow flexor','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(60,3,'ELBOW',1213,'Brachioradialis','Muscle','PRIMARY_MOVER','COMMON','Flexion in neutral (thumb-up)','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(61,3,'ELBOW',1214,'Triceps brachii','Muscle','PRIMARY_MOVER','COMMON','Elbow extension','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(62,3,'ELBOW',1215,'Anconeus','Muscle','STABILIZER','UNCOMMON','Extension assist + stabilization','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(63,3,'ELBOW',1216,'Pronator teres','Muscle','PRIMARY_MOVER','COMMON','Pronation + flexion assist','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(64,3,'ELBOW',1217,'Pronator quadratus','Muscle','PRIMARY_MOVER','COMMON','Primary pronator','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)'),
(65,3,'ELBOW',1218,'Supinator','Muscle','PRIMARY_MOVER','UNCOMMON','Supination','2026-02-20 05:10:36', 'Cozen Test','Mill Test','Hook Test (Distal Biceps)', 'Tinel (Cubital Tunnel)','ULNT3 (Ulnar Bias)','Triceps Reflex (C7)');
