INSERT INTO joints_structure (id, joint_id, joint_name, structure_id, structure_name, category_name, relationship, injury_frequency, notes, created_at, test_in_1, test_in_2, test_out_1, nerve_test_1, nerve_test_2, nerve_test_3) VALUES
(32,9,'SI JOINT',1802,'Posterior sacroiliac ligament','Ligament','PASSIVE_SUPPORT','COMMON',NULL,'2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(33,9,'SI JOINT',1804,'Iliolumbar ligament','Ligament','PASSIVE_SUPPORT','COMMON',NULL,'2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(34,9,'SI JOINT',1408,'Sciatic nerve','Nerve','NEURO','UNCOMMON','Referred pain','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(351,9,'SI JOINT',1807,'Gluteus maximus','Muscle','STABILIZER','COMMON','Force closure + hip extension influence','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(354,9,'SI JOINT',1808,'Gluteus medius','Muscle','STABILIZER','COMMON','Pelvic stability in single-leg stance','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(357,9,'SI JOINT',1809,'Multifidus','Muscle','STABILIZER','COMMON','Segmental stability (lumbar/pelvic)','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(360,9,'SI JOINT',1810,'Erector spinae','Muscle','STABILIZER','COMMON','Trunk extension + pelvic control','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(363,9,'SI JOINT',1811,'Transverse abdominis','Muscle','STABILIZER','COMMON','Core stability; load transfer','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(366,9,'SI JOINT',1812,'Internal oblique','Muscle','STABILIZER','COMMON','Core stability; pelvic control','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(369,9,'SI JOINT',1813,'Hamstrings (group)','Muscle','ASSOCIATED','COMMON','Posterior chain support','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test'),
(372,9,'SI JOINT',1814,'Latissimus dorsi','Muscle','ASSOCIATED','UNCOMMON','Thoracolumbar fascia linkage','2026-02-20 05:10:36', 'Thigh Thrust','Compression Test','Straight Leg Raise (SLR)', 'Dermatome L5','Dermatome S1','Slump Test');
