INSERT INTO joints_structure (id, joint_id, joint_name, structure_id, structure_name, category_name, relationship, injury_frequency, notes, created_at, test_in_1, test_in_2, test_out_1, nerve_test_1, nerve_test_2, nerve_test_3) VALUES
(35,10,'SPINE',1907,'Thoracolumbar disc','Disc','PASSIVE_SUPPORT','VERY_COMMON','Disc herniation','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(36,10,'SPINE',1908,'Facet joint','Bone / Articular surface','PASSIVE_SUPPORT','COMMON',NULL,'2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(37,10,'SPINE',1909,'Spinal nerve roots','Nerve','NEURO','COMMON','Radicular pain','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(375,10,'SPINE',1910,'Rectus abdominis','Muscle','PRIMARY_MOVER','COMMON','Trunk flexion','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(378,10,'SPINE',1911,'External oblique','Muscle','PRIMARY_MOVER','COMMON','Trunk rotation (opposite side) + flex assist','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(381,10,'SPINE',1912,'Internal oblique','Muscle','PRIMARY_MOVER','COMMON','Trunk rotation (same side) + stability','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(384,10,'SPINE',1913,'Transverse abdominis','Muscle','STABILIZER','COMMON','Core stability/compression','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(387,10,'SPINE',1914,'Erector spinae group','Muscle','PRIMARY_MOVER','COMMON','Trunk extension + posture','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(390,10,'SPINE',1915,'Multifidus','Muscle','STABILIZER','COMMON','Segmental stabilization','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)'),
(393,10,'SPINE',1916,'Quadratus lumborum','Muscle','PRIMARY_MOVER','COMMON','Lateral flexion + pelvic hike','2026-02-20 05:10:36', 'Kemp Test','Prone Instability Test','Babinski', 'Straight Leg Raise (SLR)','Slump Test','Patellar Reflex (L3-L4)');
