INSERT INTO joints_structure (id, joint_id, joint_name, structure_id, structure_name, category_name, relationship, injury_frequency, notes, created_at, test_in_1, test_in_2, test_out_1, nerve_test_1, nerve_test_2, nerve_test_3) VALUES
(38,11,'WRIST',2005,'Flexor retinaculum (transverse carpal ligament)','Fascia / Retinaculum','PASSIVE_SUPPORT','VERY_COMMON','Carpal tunnel','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(39,11,'WRIST',2007,'Triangular fibrocartilage complex (TFCC)','Cartilage / Labrum / Meniscus / TFCC','PASSIVE_SUPPORT','COMMON',NULL,'2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(40,11,'WRIST',2010,'Median nerve','Nerve','NEURO','VERY_COMMON','Carpal tunnel syndrome','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(396,11,'WRIST',2013,'Flexor carpi radialis (FCR)','Muscle','PRIMARY_MOVER','COMMON','Wrist flexion + radial deviation','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(399,11,'WRIST',2014,'Flexor carpi ulnaris (FCU)','Muscle','PRIMARY_MOVER','COMMON','Wrist flexion + ulnar deviation','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(402,11,'WRIST',2015,'Palmaris longus','Muscle','ASSOCIATED','UNCOMMON','Wrist flexion assist','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(405,11,'WRIST',2016,'Extensor carpi radialis longus (ECRL)','Muscle','PRIMARY_MOVER','COMMON','Wrist extension + radial deviation','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(408,11,'WRIST',2017,'Extensor carpi radialis brevis (ECRB)','Muscle','PRIMARY_MOVER','COMMON','Wrist extension + radial deviation','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)'),
(411,11,'WRIST',2018,'Extensor carpi ulnaris (ECU)','Muscle','PRIMARY_MOVER','COMMON','Wrist extension + ulnar deviation','2026-02-20 05:10:36', 'Phalen','Tinel (Carpal Tunnel)','Finkelstein', 'Median Nerve ULNT','Dermatome C6','Brachioradialis Reflex (C6)');
